src/Entity/Photo.php
<?php

namespace App\Entity;

use App\Repository\PhotoRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PhotoRepository::class)
 */
class Photo
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * Chemin sur disque dur
     * @ORM\Column(type="string", length=255)
     */
    private ?string $chemin_dd;

    /**
     * @ORM\Column(type="boolean")
     */
    private ?bool $isProfilePicture;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="photos")
     * @ORM\JoinColumn(nullable=false)
     */
    private ?User $user;

    /**
     * @ORM\ManyToMany(targetEntity=Sortie::class, mappedBy="photos")
     */
    private $sorties;

    public function __construct()
    {
        $this->sorties = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getChemindd(): ?string
    {
        return $this->chemin_dd;
    }

    public function setChemindd(string $chemin_dd): self
    {
        $this->chemin_dd = $chemin_dd;

        return $this;
    }

    public function getIsProfilePicture(): ?bool
    {
        return $this->isProfilePicture;
    }

    public function setIsProfilePicture(bool $isProfilePicture): self
    {
        $this->isProfilePicture = $isProfilePicture;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection|Sortie[]
     */
    public function getSorties(): Collection
    {
        return $this->sorties;
    }

    public function addSorty(Sortie $sorty): self
    {
        if (!$this->sorties->contains($sorty)) {
            $this->sorties[] = $sorty;
            $sorty->addPhoto($this);
        }

        return $this;
    }

    public function removeSorty(Sortie $sorty): self
    {
        if ($this->sorties->removeElement($sorty)) {
            $sorty->removePhoto($this);
        }

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\Table(name="`user`")
 * @UniqueEntity(fields={"username"}, message="Un compte avec ce nom d'utilisateur existe deja !")
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**

     * @ORM\Column(type="string", length=180, unique=true)
     */
    private string $username;

    /**
     * @ORM\Column(type="json")
     */
    private array $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private string $password;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private ?string $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private ?string $familyName;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private ?string $firstName;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private ?string $telephone;

    /**
     * @ORM\Column(type="boolean")
     */
    private ?bool $isActive;

    /**
     * @ORM\OneToMany(targetEntity=Photo::class, mappedBy="user", orphanRemoval=true, cascade={"persist"})
     */
    private $photos;

    /**
     * @ORM\ManyToOne(targetEntity=Campus::class, inversedBy="eleves")
     * @ORM\JoinColumn(nullable=false)
     */
    private ?Campus $campus;

    /**
     * @ORM\ManyToMany(targetEntity=Groupe::class, mappedBy="membres")
     */
    private $groupes;

    /**
     * @ORM\OneToMany(targetEntity=Sortie::class, mappedBy="organisateur")
     */
    private $sortiesOrganisees;

    /**
     * @ORM\ManyToMany(targetEntity=Sortie::class, mappedBy="participants")
     */
    private $sortiesParticipees;

    /**
     * @ORM\OneToMany(targetEntity=Groupe::class, mappedBy="proprietaire")
     */
    private $groupesGeres;


    public function __construct()
    {
        $this->photos = new ArrayCollection();
        $this->groupes = new ArrayCollection();
        $this->sortiesOrganisees = new ArrayCollection();
        $this->sortiesParticipees = new ArrayCollection();
        $this->groupesGeres = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->username;
    }

    /**
    * Si un utilisateur peut rejoindre
    */
    public function peutRejoindre(Sortie $sortie): bool {
        if ($sortie->getParticipants()->contains($this)) {
            return false;
        }

        if(count($sortie->getParticipants()) >= $sortie->getLimiteParticipants()) {
            return false;
        }

        return true;
    }

    /**
     * Si un utilisateur peut quitter
     */
    public function peutQuitter(Sortie $sortie): bool {
        if ($sortie->getParticipants()->contains($this)) {
            return true;
        }

        return false;
    }

    /**
     * Retourne la photo de profil si il y'en a une
     * @return Photo|null
     */
    public function getProfilePicture(): ?Photo
    {
        foreach ($this->photos as $photo) {
            if($photo->getIsProfilePicture()) {
                return $photo;
            }
        }

        return null;
    }

    /**
     * Change la photo de profile
     * @param Photo $photo
     * @return $this
     */
    public function setNewProfilePicture(Photo $photo): self
    {
        if(!empty($courant = $this->getProfilePicture())) {
            $courant->setIsProfilePicture(false);
        }

        $this->addPhoto($photo);
        $photo->setIsProfilePicture(true);

        return $this;
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->username;
    }

    /**
     * Une fonction qui affiche une version lisible
     * de la personne, pour l'afficher sur la liste
     * des gens inscrits à une sortie par exemple
     * @return string
     */
    public function getFriendlyName(): string
    {
        if($this->firstName && $this->familyName)
        {
            return "$this->firstName {$this->familyName[0]}.";
        }

        if(str_contains($this->username, '@'))
        {
            return explode('@', $this->username)[0];
        }

        return $this->username;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        //permet de garantir que les utilisateurs auront au moins ce rôle
        $roles[] = 'ROLE_USER';
        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // do not touch !!!
        // $this->password = null;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getFamilyName(): ?string
    {
        return $this->familyName;
    }

    public function setFamilyName(?string $familyName): self
    {
        $this->familyName = $familyName;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(?string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(?string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getIsAdmin(): ?bool
    {
//        return $this->isAdmin;
        return in_array('ROLE_ADMIN', $this->getRoles());
    }

    public function setIsAdmin(bool $isAdmin): self
    {
        $this->isAdmin = $isAdmin;
        $roles = $this->getRoles();
        if ($isAdmin === true)
        {
            $roles[] = 'ROLE_ADMIN';
        }
        else
        {
            unset($roles[array_search('ROLE_ADMIN', $roles)]);
        }

        $this->setRoles(array_unique($roles));
        return $this;
    }

    public function getIsActive(): ?bool
    {
        return $this->isActive;
    }

    public function setIsActive(bool $isActive): self
    {
        $this->isActive = $isActive;

        return $this;
    }

    /**
     * @return Collection|Photo[]
     */
    public function getPhotos(): Collection
    {
        return $this->photos;
    }

    public function addPhoto(Photo $photo): self
    {
        if (!$this->photos->contains($photo)) {
            $this->photos[] = $photo;
            $photo->setUser($this);
        }

        return $this;
    }

    public function removePhoto(Photo $photo): self
    {
        if ($this->photos->removeElement($photo)) {
            // set the owning side to null (unless already changed)
            if ($photo->getUser() === $this) {
                $photo->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Groupe[]
     */
    public function getGroupes(): Collection
    {
        return $this->groupes;
    }

    public function addGroupe(Groupe $groupe): self
    {
        if (!$this->groupes->contains($groupe)) {
            $this->groupes[] = $groupe;
            $groupe->addMembre($this);
        }

        return $this;
    }

    public function removeGroupe(Groupe $groupe): self
    {
        if ($this->groupes->removeElement($groupe)) {
            $groupe->removeMembre($this);
        }

        return $this;
    }

    /**
     * @return Collection|Sortie[]
     */
    public function getSortiesOrganisees(): Collection
    {
        return $this->sortiesOrganisees;
    }

    public function addSortiesOrganisee(Sortie $sortiesOrganisee): self
    {
        if (!$this->sortiesOrganisees->contains($sortiesOrganisee)) {
            $this->sortiesOrganisees[] = $sortiesOrganisee;
            $sortiesOrganisee->setOrganisateur($this);
        }

        return $this;
    }

    public function removeSortiesOrganisee(Sortie $sortiesOrganisee): self
    {
        if ($this->sortiesOrganisees->removeElement($sortiesOrganisee)) {
            // set the owning side to null (unless already changed)
            if ($sortiesOrganisee->getOrganisateur() === $this) {

templates/inc/detailsSortie.html.twig
{% import 'macros.html.twig' as macros %}
<h2 class="libelle-sortie">{{ sortie.nom }}</h2>

<div class="row">
    <div class="col-md-3">
        {% for photo in sortie.photos %}
        <img class="image-sorties" src="{{ asset(photos_path ~ photo.chemindd) }}" alt="photo de la sortie"/>
        {% endfor %}
    </div>
    <div class="col-md-9">
        <div>Date : le {{ sortie.dateDebut|date("d/m/Y")}}, de {{ sortie.heureDebut|date('H:i') }} à {{ sortie.heureFin|date('H:i') }}</div>
        <div>Campus : {{ sortie.campus.nom }}</div>
        <div>Thématique : {{ sortie.theme.theme }}</div>
        <div>Lieu : {{ sortie.lieu.nom }} à {{ sortie.lieu.ville.nom }}</div>
        <div>Description : {{ sortie.infosSortie }}</div>
        <div>Organisateur :
            <a href="{{ path('user_show', {'id': sortie.organisateur.id}) }}">
                {{ sortie.organisateur.friendlyName }}
            </a>
        </div>
        <div>Nombre maximal de participants : {{ sortie.limiteParticipants }}</div>
        <div>Nombre d'inscrits : {{ sortie.participants|length }}
            {{ macros.liste_utilisateurs(sortie.participants) }}
        </div>
        <div>Nombre de places restantes : {{ sortie.limiteParticipants-sortie.participants|length }} / {{ sortie.limiteParticipants }}</div>
        <div>Date limite d'inscription : {{ sortie.dateCloture|date("d/m/Y") }}</div>
    </div>
</div>

templates/inc/inscriptionSortie.html.twig
{% if app.user %}
    {% dump app.user.id %}
    {% if app.user.sortiesParticipees.contains(sortie) %}
        <h3>Vous êtes inscrit à cette sortie</h3>
        {# Si on est inscrit à la sortie alors on peut cliquer sur le bouton pour se désinscrire #}
        {{ form(desinscriptionSortieForm) }}
    {% else %}
        {% if sortie.dateCloture|date('Y-m-d') >= date("now")|date('Y-m-d') %}
            {% if sortie.participants|length < sortie.limiteParticipants %}
        {# Si on n'est pas inscrit à la sortie alors on peut cliquer sur le bouton pour s'inscrire #}
                {{ form(inscriptionSortieForm) }}
            {% else %}
                <h3>Il n'y plus de places disponibles</h3>
            {% endif %}
        {% else %}
            <h3>La date limite d'inscription est dépassée</h3>
        {% endif %}
    {% endif %}

{% else %}
    <h3>Pour pouvoir s'inscrire, veuillez vous connecter à votre compte utilisateur</h3>
    <li><a href="{{ path('app_login') }}" title="Se connecter">Se connecter</a></li>
    <li><a href="{{ path('app_register') }}" title="S'inscrire'">Créer un compte</a></li>
{% endif %}

templates/inc/nav.html.twig
<nav class="navigation navbar navbar-expand-md  navbar-dark bg-dark">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="header-logo navbar-brand" href="{{ path('main_home') }}" title="Accueil">
            <img class="logoENI" src="{{ asset('img/logo_ENI_global.svg') }}" alt="logo ENI">
            <h1 class="d-md-none"><a href="{{ path('main_home') }}">Sortir.com</a></h1>
        </a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav" >
                {#        <li><a href="{{ path('sorties_findSelect') }}" title="Liste des sorties">Sorties</a></li>#}

                {%  if app.user %}
                    <li class="nav-item">
                        <a href="{{ path('user_show', {'id': app.user.id}) }}" title="Profil">
                            {% if app.user.profilePicture is defined and app.user.profilePicture is not null %}
                                <img
                                        src="{{ asset(photos_path ~ app.user.profilePicture.chemindd) }}"
                                        alt="photo de profil"
                                        width="20"
                                        height="20"
                                        style="border-radius: 50%; width: 20px; height: 20px"
                                />
                            {% endif %}

                            {{ app.user.userIdentifier }}
                        </a>
                        {% if app.user.isAdmin %}
                            ⚔
                        {% else %}
                            👤
                        {% endif %}
                    </li>
                    <li class="nav-item"><a href="{{ path('app_logout') }}" title="Se déconnecter">Se déconnecter</a> </li>
                    <li class="nav-item"><a href="{{ path('sorties_create') }}" title="Proposer une sortie">Créer une sortie</a></li>
                    <li class="nav-item"><a href="{{ path('lieu_index') }}">Liste des lieux</a></li>

                    {% if is_granted("ROLE_ADMIN") %}
                        <li class="nav-item"><a href="{{ path('admin_dashboard') }}" title="Admin Dashboard">Administrateur</a> </li>
                    {% endif %}

                {% else %}
                    <li class="nav-item"><a href="{{ path('app_login') }}" title="Se connecter">Se connecter</a> </li>
                    <li class="nav-item"><a href="{{ path('app_register') }}" title="S'inscrire'">S'inscrire</a> </li>
                {% endif %}
            </ul>
        </div>

    </div>

</nav>